### ISSUE TITLE
PlaceableItems mod VS CarryOn mod

### ISSUE THREAD

**Issue by ano19920** [Ferdzz/PlaceableItems#24] opened 2017-08-16 07:42 UTC
I love both of these mods but they apparently don't get along. I hope this bug is an easy fix! I sent this to CarryOn and now I'm sending it to you, too.

https://pastebin.com/v3Jkxt1Q

**Comment by Ferdzz** [comment] 2017-08-17 00:51
Thank you for reporting this. Can you tell me more about the crash? Was it caused by an action you did in-game or during the loading?

**Comment by Ferdzz** [comment] 2017-10-12 02:29
Since no news have been given, I am closing this issue. Please feel free to open a new issue if you're still experiencing problems.

**Closed by Ferdzz** 2017-10-12 02:29 UTC
