### ISSUE TITLE
Placing key

### ISSUE THREAD

**Issue by AlyaqdhanZ** [Ferdzz/PlaceableItems#81] opened 2020-05-20 21:08 UTC
Add the ability to change placing key because sometimes when I hold bucket of water and shift to not fall I place it by wrong, I hope you get it, thanks.

**Comment by Ferdzz** [comment] 2020-05-21 00:16
Duplicate of #13 

This has been released on version 4.1

**Closed by Ferdzz** 2020-05-21 00:16 UTC
Labels: duplicate, enhancement

**Comment by AlyaqdhanZ** [comment] 2020-05-21 00:29
But 4.1 on version 1.14 isn't it?
I'm playing in 1.12 :)

**Comment by Ferdzz** [comment] 2020-05-21 14:38
Please read the [FAQ](https://www.curseforge.com/minecraft/mc-mods/placeable-items) on the subject of backporting features. 

Unless someone wants to do a PR to implement this on 1.12, this will not be done
