### ISSUE TITLE
Placing music discs

### ISSUE THREAD

**Issue by NighthowlerNorway** [Ferdzz/PlaceableItems#107] opened 2022-04-22 22:04 UTC
When placing a music disc the game crashes, and the world is corrupt. Maybe make it not placeable til this issue is fixed?

**Comment by Ferdzz** [comment] 2022-04-25 14:24
Please use the bug template and include the version information

**Comment by Ferdzz** [comment] 2022-04-29 13:08
Closing as duplicate of #108

**Closed by Ferdzz** 2022-04-29 13:08 UTC
Labels: duplicate
