### ISSUE TITLE
Crash when wrenching a TD fluid duct off of a Tinkers smeltery drain.

### ISSUE THREAD

**Issue by MoxieGrrl** [Ferdzz/PlaceableItems#5] opened 2015-07-19 18:30 UTC
[Here's the crash report.](http://pastebin.com/kQNHBrHW)

Seems to happen only sometimes. Stops happening when this mod is removed. Crashes the client to desktop when in single player but only causes the client to get booted on a server.

**Comment by Ferdzz** [comment] 2015-07-19 23:53
Thanks for bringing this up. What version of Placeable Items were you using?

**Comment by Ferdzz** [comment] 2015-07-20 00:19
Can you test it out with the latest version ? (1.4.4 http://minecraft.curseforge.com/mc-mods/227951-placeable-items-v1-4-4/files/2248095)

**Comment by MoxieGrrl** [comment] 2015-07-23 23:42
Will do tonight.

**Comment by MoxieGrrl** [comment] 2015-07-24 03:23
Still crashes. [Here's the report.](http://pastebin.com/rHPrwQ0d)

**Comment by emx2000** [comment] 2015-07-25 12:38
Hello, MoxieGrrl.

I apologize for the lack of replies, we are trying hard to solve the issue, however I am currently unable to reproduce the crash you mentioned, so that contributes to the slow solution for this issue.

I have pushed a possible fix for version 1.4.4, please download and try out the bugfix version 1.4.4.1, via the project site as soon as it's been uploaded by Ferdzz.

**Comment by Ferdzz** [comment] 2015-12-24 20:29
This issue has been fixed as of [version 1.4.4.1](http://minecraft.curseforge.com/projects/placeable-items-v1-4-4-1/files/2248879)

**Closed by Ferdzz** 2015-12-24 20:29 UTC
Labels: bug, fatal
